import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Limelight, Arizonia, Fuzzy_Bubbles } from "next/font/google";
import "./globals.css";
import "@fontsource/mozilla-headline/400.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";


// Whenever you want to change the font, just grab the one you want from next/font/google in
// src/app/layout.tsx
// pass its variable into the HTML tag, and then point --font-sans to that variable in
// src/app/globals.css

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const limelight = Limelight({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-limelight",
});

const arizonia = Arizonia({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-arizonia",
});

const fuzzyBubbles = Fuzzy_Bubbles({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-fuzzy-bubbles",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", jetbrainsMono.variable, arizonia.variable, fuzzyBubbles.variable)}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
